[package]
name = "sample"
version = "0.1.0"
authors = ["Nikolay Volf <nikvolf@gmail.com>"]
edition = "2018"

[dependencies]
hashbrown = { version = "*", default-features = false }

[dev-dependencies]
async-std = { version = "*", default-features = false }


[workspace]